[package]
name = "lm-render"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
lm-core.workspace = true
lm-geom.workspace = true
lm-media.workspace = true
egui-wgpu.workspace = true
log.workspace = true
egui.workspace = true

[dev-dependencies]
naga = { version = "30", features = ["wgsl-in"] }
